(()=>{
"use strict";
const MAG="https://services.swpc.noaa.gov/json/rtsw/rtsw_mag_1m.json";
const WIND="https://services.swpc.noaa.gov/json/rtsw/rtsw_wind_1m.json";
const KP="https://services.swpc.noaa.gov/json/planetary_k_index_1m.json";
const OVATION="https://services.swpc.noaa.gov/json/ovation_aurora_latest.json";
let loaded=false, charts=[];
const $=id=>document.getElementById(id);
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const fmt=(v,d=1)=>v==null?"–":v.toLocaleString("de-DE",{minimumFractionDigits:d,maximumFractionDigits:d});
function active(rows){const a=rows.filter(r=>r&&r.active!==false);return a.length?a:rows}
function latest(rows,fields){for(let i=rows.length-1;i>=0;i--){if(fields.every(f=>num(rows[i]?.[f])!=null))return rows[i]}return null}
function set(id,value,detail){if($(id))$(id).textContent=value;if(detail!==undefined&&$(id+"Detail"))$(id+"Detail").textContent=detail}
function chart(id,labels,sets,scale){const el=$(id);if(!el)return;const old=Chart.getChart(el);if(old)old.destroy();charts.push(new Chart(el,{type:"line",data:{labels,datasets:sets},options:{responsive:true,maintainAspectRatio:false,animation:false,interaction:{mode:"index",intersect:false},plugins:{legend:{display:true},datalabels:{display:false}},scales:{x:{ticks:{maxTicksLimit:8}},y:{title:{display:true,text:scale}}}}}))}
function slice2h(rows){const cut=Date.now()-2*3600e3;return active(rows).filter(r=>new Date((r.time_tag||"")+"Z").getTime()>=cut)}
function labels(rows){return rows.map(r=>new Date((r.time_tag||"")+"Z").toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"}))}
function localOvation(data,lat,lon){const coords=data?.coordinates||data?.Coordinate||[];if(!Array.isArray(coords)||!coords.length)return null;let best=null,dist=Infinity;const L=((lon%360)+360)%360;for(const p of coords){if(!Array.isArray(p)||p.length<3)continue;const d=(Number(p[1])-lat)**2+Math.min(Math.abs(Number(p[0])-L),360-Math.abs(Number(p[0])-L))**2*Math.cos(lat*Math.PI/180)**2;if(d<dist){dist=d;best=p}}return best?Number(best[2]):null}
function assess(bz,bt,speed,prob,lat){let s=0;if(bz!=null)s+=bz<=-8?35:bz<=-5?28:bz<=-3?20:bz<0?10:0;if(bt!=null)s+=bt>=15?20:bt>=10?15:bt>=5?8:2;if(speed!=null)s+=speed>=700?20:speed>=550?15:speed>=400?9:3;if(prob!=null)s+=Math.min(20,prob/3);if(lat!=null&&Math.abs(lat)>=65)s+=8;return Math.min(100,s)}
async function load(force=false){if(loaded&&!force)return;const dot=$("auroraLiveDot"),status=$("auroraStatus");try{if(dot)dot.className="aurora-dot";const [mr,wr,kr,or]=await Promise.all([MAG,WIND,KP,OVATION].map(u=>fetch(u,{cache:"no-store"}).then(r=>{if(!r.ok)throw Error("HTTP "+r.status);return r.json()})));const m=active(mr),w=active(wr),ml=latest(m,["bt","bz_gsm"]),wl=latest(w,["proton_speed","proton_density"]),kl=latest(kr,["kp_index"]);const bz=num(ml?.bz_gsm),bt=num(ml?.bt),speed=num(wl?.proton_speed),density=num(wl?.proton_density),kp=num(kl?.kp_index);set("auroraBz",fmt(bz)+" nT",bz==null?"keine Daten":bz<=-5?"stark südwärts":bz<=-3?"günstig":bz<0?"leicht südwärts":"nordwärts");set("auroraBt",fmt(bt)+" nT");set("auroraSpeed",fmt(speed,0)+" km/s");set("auroraDensity",fmt(density)+" p/cm³");set("auroraKp",fmt(kp));const lead=speed?Math.round(1500000/speed/60):null;set("auroraLead",lead?("~"+lead+" min"):"–","grobe L1→Erde-Laufzeit");const mm=slice2h(mr),ww=slice2h(wr);chart("auroraMagChart",labels(mm),[{label:"Bz GSM",data:mm.map(r=>num(r.bz_gsm)),borderColor:"#2563eb",pointRadius:0,borderWidth:2},{label:"Bt",data:mm.map(r=>num(r.bt)),borderColor:"#111827",pointRadius:0,borderWidth:1.5}],"nT");chart("auroraWindChart",labels(ww),[{label:"Solarwind",data:ww.map(r=>num(r.proton_speed)),borderColor:"#b45309",pointRadius:0,borderWidth:2}],"km/s");chart("auroraDensityChart",labels(ww),[{label:"Protonendichte",data:ww.map(r=>num(r.proton_density)),borderColor:"#7c3aed",pointRadius:0,borderWidth:2}],"p/cm³");window.__auroraOvation=or;window.__auroraNow={bz,bt,speed};if(dot)dot.className="aurora-dot live";if($("auroraUpdated"))$("auroraUpdated").textContent="Live · "+new Date().toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"});updateAssessment();loaded=true}catch(e){console.error("Aurora dashboard",e);if(dot)dot.className="aurora-dot error";if($("auroraUpdated"))$("auroraUpdated").textContent="Live-Daten konnten nicht geladen werden";if(status)status.querySelector(".aurora-status-title").textContent="Datenfehler – erneut laden";}}
function updateAssessment(){const lat=num($("auroraLat")?.dataset.value),lon=num($("auroraLon")?.dataset.value);let prob=null;if(lat!=null&&lon!=null&&window.__auroraOvation){prob=localOvation(window.__auroraOvation,lat,lon);set("auroraProbability",prob==null?"–":fmt(prob,0)+" %","OVATION, nächster Gitterpunkt")}const n=window.__auroraNow||{},score=assess(n.bz,n.bt,n.speed,prob,lat),box=$("auroraStatus"),title=box?.querySelector(".aurora-status-title"),detail=$("auroraAssessmentDetail");if(!box||!title)return;box.classList.remove("good","watch","strong");if(score>=65){box.classList.add("strong");title.textContent="Sehr interessante Aurora-Lage";}else if(score>=42){box.classList.add("good");title.textContent="Aurora-Lage interessant";}else if(score>=25){box.classList.add("watch");title.textContent="Aurora möglich – Entwicklung beobachten";}else title.textContent="Aktuell eher ruhige Aurora-Lage";if(detail)detail.textContent=lat==null?"Standort freigeben für die lokale OVATION-Einschätzung.":("Bewertung für "+Math.abs(lat).toFixed(2)+"° "+(lat>=0?"N":"S")+" · Sonnenwind + IMF + lokale OVATION-Wahrscheinlichkeit.");}
async function locate(){const b=$("auroraLocate"),out=$("auroraLocationText");if(!window.isSecureContext){if(out)out.textContent="Standortzugriff benötigt HTTPS.";return}if(!navigator.geolocation){if(out)out.textContent="Standortbestimmung wird von diesem Browser nicht unterstützt.";return}if(b){b.disabled=true;b.textContent="Standort wird bestimmt …"}if(out)out.textContent="GPS/Standort wird angefragt …";try{if(navigator.permissions?.query){const permission=await navigator.permissions.query({name:"geolocation"}).catch(()=>null);if(permission?.state==="denied"){if(out)out.textContent="Standort ist für diese Website blockiert. Bitte in den Website-Berechtigungen „Standort“ erlauben.";if(b){b.disabled=false;b.textContent="Erneut versuchen"}return}}}catch(_e){}navigator.geolocation.getCurrentPosition(p=>{const lat=p.coords.latitude,lon=p.coords.longitude;$("auroraLat").dataset.value=lat;$("auroraLon").dataset.value=lon;if(out)out.textContent=lat.toFixed(4)+"°, "+lon.toFixed(4)+"° · Genauigkeit ±"+Math.round(p.coords.accuracy)+" m";if(b){b.disabled=false;b.textContent="Standort aktualisieren"}updateAssessment();},e=>{if(b){b.disabled=false;b.textContent="Erneut versuchen"}let msg="Standort konnte nicht bestimmt werden.";if(e.code===1)msg="Standortberechtigung verweigert. Bitte für diese Website den Standort erlauben.";else if(e.code===2)msg="Position momentan nicht verfügbar. Bitte GPS/Standort am Handy aktivieren und erneut versuchen.";else if(e.code===3)msg="Standortabfrage hat zu lange gedauert. Bitte erneut versuchen – am besten mit freier Sicht nach draußen.";if(out)out.textContent=msg;console.warn("Aurora Geolocation:",e.code,e.message);},{enableHighAccuracy:true,timeout:25000,maximumAge:60000})}
function bindAuroraControls(){const refresh=$("auroraRefresh"),loc=$("auroraLocate");if(refresh&&!refresh.dataset.bound){refresh.dataset.bound="1";refresh.addEventListener("click",()=>load(true))}if(loc&&!loc.dataset.bound){loc.dataset.bound="1";loc.addEventListener("click",locate)}const requested=new URL(window.location.href).searchParams.get("tab");if(requested==="aurora"&&typeof window.switchTab==="function"){window.setTimeout(()=>window.switchTab("aurora",{persist:false}),0)}}
window.ensureAuroraDashboard=()=>{bindAuroraControls();return load(false)};
bindAuroraControls();
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bindAuroraControls,{once:true});
})();