(()=>{"use strict";
const BASE="europe_stations/dwd_daily_map/",MODES={tmax_anom:["Tmax-Anomalie",3,"anom"],tmean_anom:["Tmean-Anomalie",12,"anom"],tmin_anom:["Tmin-Anomalie",4,"anom"],tmax:["Tmax",1,"tmax"],tmean:["Tmean",11,"tmean"],tmin:["Tmin",2,"tmin"],records:["Stationsrekorde",null,"records"],summer_days:["Sommertage · Rekordabstand","summer_days","climate"],hot_days:["Hitzetage · Rekordabstand","hot_days","climate"],very_hot_days:["≥35 °C · Rekordabstand","very_hot_days","climate"],tropical_nights:["Tropennächte · Rekordabstand","tropical_nights","climate"],frost_days:["Frosttage · Rekordabstand","frost_days","climate"],ice_days:["Eistage · Rekordabstand","ice_days","climate"]};
let idx=null,map=null,layer=null,renderer=null,cache=new Map(),climateCache=null,selected=null,bound=false;
const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const tenth=v=>(v===null||v===undefined||v==="")?null:(Number.isFinite(Number(v))?Number(v)/10:null);
const temp=v=>tenth(v)==null?"–":tenth(v).toLocaleString("de-DE",{minimumFractionDigits:1,maximumFractionDigits:1})+" °C";
const anom=v=>tenth(v)==null?"–":(tenth(v)>0?"+":"")+tenth(v).toLocaleString("de-DE",{minimumFractionDigits:1,maximumFractionDigits:1})+" K";
const datefmt=v=>v?new Date(v+"T12:00:00").toLocaleDateString("de-DE"):"–";
function inject(){
 if($("dwdDailyMap"))return;
 const link=document.createElement("link");link.rel="stylesheet";link.href="dwd_station_daily_map.css?v=2";document.head.appendChild(link);
 const menu=document.querySelector('.nav-dropdown[data-nav-group="stations"] .nav-dropdown-menu');
 if(menu&&!menu.querySelector('[data-dwd-daily]')){const b=document.createElement("button");b.className="tab-button";b.dataset.navGroup="stations";b.dataset.dwdDaily="1";b.textContent="DWD Tageskarte";b.onclick=()=>{switchTab("dwdDailyMap");setTimeout(load,0)};const anchor=menu.querySelector('[onclick*="stationObservations"]');(anchor?.nextSibling?menu.insertBefore(b,anchor.nextSibling):menu.appendChild(b));}
 const tab=document.createElement("div");tab.id="dwdDailyMap";tab.className="tab-content";tab.innerHTML=`
 <div class="section-header"><h2>DWD Tageskarte</h2><p>Tageswerte, Anomalien, Kalendertagsrekorde und aktueller Abstand zu jährlichen Kenntage-Rekorden aller verfügbaren DWD-KL-Stationen.</p><span class="section-status">DWD CDC Tageswerte KL · TXK/TNK/TMK · Referenz 1991–2020</span></div>
 <div class="dwd-daily-shell">
  <aside class="dwd-daily-card"><div class="dwd-daily-controls">
   <div class="control-group"><label for="dwdDailyMetric">Darstellung</label><select id="dwdDailyMetric"><optgroup label="Tageswerte"><option value="tmax_anom">Tmax-Anomalie</option><option value="tmean_anom">Tmean-Anomalie</option><option value="tmin_anom">Tmin-Anomalie</option><option value="tmax">Tmax absolut</option><option value="tmean">Tmean absolut</option><option value="tmin">Tmin absolut</option><option value="records">Stationsrekorde</option></optgroup><optgroup label="Kenntage · Abstand zum Jahresrekord"><option value="summer_days">Sommertage ≥25 °C</option><option value="hot_days">Hitzetage ≥30 °C</option><option value="very_hot_days">Sehr heiße Tage ≥35 °C</option><option value="tropical_nights">Tropennächte ≥20 °C</option><option value="frost_days">Frosttage &lt;0 °C</option><option value="ice_days">Eistage &lt;0 °C</option></optgroup></select></div>
   <div class="control-group"><label>Datum</label><div class="dwd-daily-date-nav"><button id="dwdDailyPrev">‹</button><input id="dwdDailyDate" type="date"><button id="dwdDailyNext">›</button></div></div>
   <p id="dwdDailyReference" class="note">Referenz wird geladen …</p>
  </div><div id="dwdDailyStatus" class="dwd-daily-status">Daten werden geladen …</div>
  <div class="dwd-daily-kpis"><div class="dwd-daily-kpi"><div class="label">Stationen</div><div id="dwdDailyStationCount" class="value">–</div></div><div class="dwd-daily-kpi"><div class="label">mit Anomalie</div><div id="dwdDailyAnomalyCount" class="value">–</div></div><div class="dwd-daily-kpi"><div class="label">Rekordstationen</div><div id="dwdDailyRecordCount" class="value">–</div></div><div class="dwd-daily-kpi"><div class="label">Datenstand</div><div id="dwdDailyDataThrough" class="value">–</div></div></div></aside>
  <section class="dwd-daily-card"><div id="dwdDailyStationMap" class="dwd-daily-map"></div><div id="dwdDailyLegend" class="dwd-daily-legend"></div><div id="dwdDailySelected" class="dwd-daily-selected"><h3>Station auswählen</h3><p>Klicke einen Stationspunkt oder einen Ranglisten-Eintrag an.</p></div></section>
  <aside class="dwd-daily-side"><div class="dwd-daily-card"><h3 id="dwdDailyTopTitle">Top 10</h3><div id="dwdDailyTopList" class="dwd-daily-list"></div></div><div class="dwd-daily-card"><h3 id="dwdDailyBottomTitle">Bottom 10</h3><div id="dwdDailyBottomList" class="dwd-daily-list"></div></div><div class="dwd-daily-card"><h3 id="dwdDailyRecordTitle">Rekorde des Tages</h3><p id="dwdDailyRecordSummary" class="note">–</p><div id="dwdDailyRecordList" class="dwd-daily-list"></div></div></aside>
 </div>`;
 document.querySelector("main.dashboard-main")?.appendChild(tab);
 const mobile=$("mobileTabSelect");if(mobile&&!mobile.querySelector('option[value="dwdDailyMap"]')){const o=document.createElement("option");o.value="dwdDailyMap";o.textContent="DWD Tageskarte";mobile.appendChild(o);mobile.addEventListener("change",()=>{if(mobile.value==="dwdDailyMap")setTimeout(load,0)})}
}
async function gunzip(url){const r=await fetch(url,{cache:"no-store"});if(!r.ok)throw Error("HTTP "+r.status);const b=new Uint8Array(await r.arrayBuffer());if(b[0]===31&&b[1]===139){if(!window.DecompressionStream)throw Error("gzip wird vom Browser nicht unterstützt");const s=new Blob([b]).stream().pipeThrough(new DecompressionStream("gzip"));return JSON.parse(await new Response(s).text())}return JSON.parse(new TextDecoder().decode(b))}
async function index(){if(idx)return idx;const r=await fetch(BASE+"index.json?v="+Date.now(),{cache:"no-store"});if(!r.ok)throw Error("HTTP "+r.status);idx=await r.json();if(!idx.ready)throw Error("Tageskarten-Daten sind noch nicht erzeugt");return idx}
async function day(iso){const md=iso.slice(5);if(!cache.has(md))cache.set(md,gunzip(BASE+"calendar/"+md+".json.gz?v="+encodeURIComponent(idx.generated_at||"")));return cache.get(md)}
async function climate(){if(!climateCache){const r=await fetch(BASE+(idx.climate_days_file||"climate_days.json")+"?v="+encodeURIComponent(idx.generated_at||""),{cache:"no-store"});if(!r.ok)throw Error("HTTP "+r.status);climateCache=await r.json()}return climateCache}
function station(i){const s=idx.stations[i];return s&&{i,id:s[0],dwd:s[1],name:s[2],lat:+s[3],lon:+s[4],elev:s[5],state:s[6]||""}}
function mode(){const k=$("dwdDailyMetric")?.value||"tmax_anom";return [k,...MODES[k]]}
function acol(v){const n=tenth(v);if(n==null)return"#aeb6bc";return n<=-8?"#233b75":n<=-5?"#3f69a8":n<=-3?"#6f9bc3":n<=-1?"#b8d1df":n<1?"#ecebe5":n<3?"#efc6a8":n<5?"#dc8b62":n<8?"#bd5140":"#7f1d2d"}
function tcol(v,max){const n=tenth(v);if(n==null)return"#aeb6bc";if(max)return n<0?"#466f9d":n<10?"#7da6a5":n<20?"#9dbb78":n<25?"#d5c568":n<30?"#e3a04e":n<35?"#d66f43":n<40?"#b83e37":"#7b1d2b";return n<-20?"#35275f":n<-10?"#4f66a6":n<0?"#79a6c7":n<10?"#a9c9ba":n<15?"#d6cb82":n<20?"#dfa05d":n<25?"#cc684d":"#963342"}
function tmcol(v){const n=tenth(v);if(n==null)return"#aeb6bc";return n<-10?"#3f4d86":n<0?"#668bb1":n<10?"#9abfb9":n<15?"#d0c879":n<20?"#e2aa58":n<25?"#d77848":n<30?"#b6453d":"#7f2430"}
function climateColor(v){const n=Number(v);if(!Number.isFinite(n))return"#aeb6bc";return n<=-20?"#355a8a":n<=-10?"#6689ad":n<=-5?"#9eb5c8":n<0?"#d5dfe5":n===0?"#e4c767":n<5?"#e7b09d":n<10?"#d8735f":"#a73535"}
function climateDiff(v){const n=Number(v);if(!Number.isFinite(n))return"–";return(n>0?"+":"")+n.toLocaleString("de-DE")+" Tage"}
function color(r,m){return m[3]==="anom"?acol(r?.[m[2]]):m[3]==="tmax"?tcol(r?.[m[2]],1):m[3]==="tmean"?tmcol(r?.[m[2]]):m[3]==="tmin"?tcol(r?.[m[2]],0):r?.[5]&&r?.[6]?"#6c3c91":r?.[5]?"#b83332":r?.[6]?"#315f9e":"#b9c0c5"}
function val(r,m){if(m[3]==="anom")return anom(r?.[m[2]]);if(m[3]==="tmax"||m[3]==="tmean"||m[3]==="tmin")return temp(r?.[m[2]]);const x=[];if(r?.[5])x.push("Tmax "+(r[5]===1?"NEU":"eingestellt"));if(r?.[6])x.push("Tmin "+(r[6]===1?"NEU":"eingestellt"));return x.join(" · ")||"kein Rekord"}
function legend(m){let a=m[3]==="climate"?[["≤ −20","#355a8a"],["−10","#6689ad"],["−5","#9eb5c8"],["−1","#d5dfe5"],["0 · eingestellt","#e4c767"],["+1 bis +4","#e7b09d"],["+5","#d8735f"],["≥ +10","#a73535"]]:m[3]==="anom"?[["≤ −8 K","#233b75"],["−5","#3f69a8"],["−3","#6f9bc3"],["±0","#ecebe5"],["+3","#dc8b62"],["+5","#bd5140"],["≥ +8 K","#7f1d2d"]]:m[3]==="records"?[["Tmax-Rekord","#b83332"],["Tmin-Rekord","#315f9e"],["beides","#6c3c91"]]:m[3]==="tmax"?[["<0","#466f9d"],["10","#7da6a5"],["20","#9dbb78"],["30","#e3a04e"],["35","#d66f43"],["≥40 °C","#7b1d2b"]]:m[3]==="tmean"?[["<−10","#3f4d86"],["0","#668bb1"],["10","#9abfb9"],["15","#d0c879"],["20","#e2aa58"],["25","#d77848"],["≥30 °C","#7f2430"]]:[["<−20","#35275f"],["−10","#4f66a6"],["0","#79a6c7"],["10","#a9c9ba"],["20","#dfa05d"],["≥25 °C","#963342"]];$("dwdDailyLegend").innerHTML=a.map(x=>`<span><i style="background:${x[1]}"></i>${x[0]}</span>`).join("")}
function initMap(){if(map||!$("dwdDailyStationMap")||!window.L)return;map=L.map("dwdDailyStationMap",{preferCanvas:true,minZoom:5,maxZoom:12,maxBounds:[[46.2,4.3],[56.2,16.8]],maxBoundsViscosity:.75});L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(map);renderer=L.canvas({padding:.4});layer=L.layerGroup().addTo(map);map.fitBounds([[47,5.5],[55.2,15.6]])}
function detail(s,r,iso){$("dwdDailySelected").innerHTML=`<h3>${esc(s.name)}</h3><p>${esc(s.state||"Deutschland")} · DWD ${esc(s.dwd)} · ${datefmt(iso)}</p><div class="dwd-daily-detail-grid"><div><span>Höhe</span><strong>${s.elev==null?"–":Math.round(s.elev)+" m"}</strong></div><div><span>Tmax</span><strong>${temp(r[1])}</strong></div><div><span>Tmean</span><strong>${temp(r[11])}</strong></div><div><span>Tmin</span><strong>${temp(r[2])}</strong></div><div><span>Tmax-Anomalie</span><strong>${anom(r[3])}</strong><small>${r[9]||0} Ref.-Jahre</small></div><div><span>Tmean-Anomalie</span><strong>${anom(r[12])}</strong><small>${r[13]||0} Ref.-Jahre</small></div><div><span>Tmin-Anomalie</span><strong>${anom(r[4])}</strong><small>${r[10]||0} Ref.-Jahre</small></div><div><span>Tmax-Rekord bisher</span><strong>${temp(r[7])}</strong><small>${r[5]?(r[5]===1?"neu gebrochen":"eingestellt"):"nicht erreicht"}</small></div><div><span>Tmin-Rekord bisher</span><strong>${temp(r[8])}</strong><small>${r[6]?(r[6]===1?"neu gebrochen":"eingestellt"):"nicht erreicht"}</small></div></div>`}
function climateDetail(s,row,metric,meta){const years=(row[4]||[]).join(", ")||"–";$("dwdDailySelected").innerHTML=`<h3>${esc(s.name)}</h3><p>${esc(s.state||"Deutschland")} · DWD ${esc(s.dwd)} · Stand ${datefmt(row[6]||meta.data_through)}</p><div class="dwd-daily-detail-grid"><div><span>Kenntag</span><strong>${esc(meta.label)}</strong><small>${esc(meta.definition)}</small></div><div><span>${idx.year}</span><strong>${row[1]} Tage</strong><small>${row[5]} gültige Tageswerte</small></div><div><span>Bisheriger Rekord</span><strong>${row[2]} Tage</strong><small>${esc(years)}</small></div><div><span>Rekordabstand</span><strong>${climateDiff(row[3])}</strong><small>${row[3]>0?"Rekord übertroffen":row[3]===0?"Rekord eingestellt":"noch bis zum Rekord"}</small></div></div>`}
function climateRowsHtml(a){return a.length?a.map(x=>`<button class="dwd-daily-row dwd-daily-row-colored" data-i="${x.s.i}" style="--dwd-row-color:${climateColor(x.r[3])}"><span><b>${esc(x.s.name)}</b><small>${x.r[1]} / Rekord ${x.r[2]}</small></span><strong>${climateDiff(x.r[3])}</strong></button>`).join(""):'<div class="dwd-daily-empty">Keine passenden Stationen.</div>'}
function rowsHtml(a,m){return a.length?a.map(x=>{const c=color(x.r,m);return `<button class="dwd-daily-row dwd-daily-row-colored" data-i="${x.s.i}" style="--dwd-row-color:${c}"><span><b>${esc(x.s.name)}</b><small>${esc(x.s.state||"DWD "+x.s.dwd)}</small></span><strong>${esc(val(x.r,m))}</strong></button>`}).join(""):'<div class="dwd-daily-empty">Keine passenden Stationen.</div>'}
function renderClimate(payload){const m=mode(),metric=m[2],meta=payload.metrics?.[metric];if(!meta)throw Error("Kenntage-Daten fehlen für "+metric);const rm=new Map((meta.rows||[]).map(r=>[+r[0],r]));legend(m);initMap();layer.clearLayers();$("dwdDailyStationCount").textContent=rm.size.toLocaleString("de-DE");const reached=[...rm.values()].filter(r=>r[3]>=0).length,broken=[...rm.values()].filter(r=>r[3]>0).length,tied=[...rm.values()].filter(r=>r[3]===0).length;$("dwdDailyAnomalyCount").textContent=reached.toLocaleString("de-DE");$("dwdDailyRecordCount").textContent=broken.toLocaleString("de-DE");$("dwdDailyDataThrough").textContent=datefmt(payload.data_through);
 for(let i=0;i<idx.stations.length;i++){const s=station(i);if(!s||!Number.isFinite(s.lat)||!Number.isFinite(s.lon))continue;const r=rm.get(i),has=!!r;const mk=L.circleMarker([s.lat,s.lon],{renderer,radius:has?5.2:3.2,weight:has?1.15:.55,color:"#26313a",opacity:has?.95:.48,fillColor:has?climateColor(r[3]):"#aeb6bc",fillOpacity:has?.92:.25}).bindTooltip("<b>"+esc(s.name)+"</b><br>"+(has?esc(meta.label)+": "+r[1]+" · Rekord "+r[2]+" · "+esc(climateDiff(r[3])):"keine ausreichenden Daten"));mk.on("click",()=>{if(r){selected=i;climateDetail(s,r,metric,meta)}});mk.addTo(layer)}
 const avail=[...rm].map(([i,r])=>({s:station(i),r,v:+r[3]})).filter(x=>x.s);const top=[...avail].sort((a,b)=>b.v-a.v).slice(0,10),bottom=[...avail].sort((a,b)=>a.v-b.v).slice(0,10);$("dwdDailyTopTitle").textContent="Größte Rekordüberschreitung";$("dwdDailyBottomTitle").textContent="Größter Abstand zum Rekord";$("dwdDailyTopList").innerHTML=climateRowsHtml(top);$("dwdDailyBottomList").innerHTML=climateRowsHtml(bottom);$("dwdDailyRecordTitle").textContent="Kenntage-Rekordstand";$("dwdDailyRecordSummary").textContent=`${reached}/${rm.size} Stationen Rekord erreicht · ${broken} übertroffen · ${tied} eingestellt`;$("dwdDailyRecordList").innerHTML=avail.filter(x=>x.r[3]>=0).sort((a,b)=>b.v-a.v).slice(0,30).map(x=>`<button class="dwd-daily-row" data-i="${x.s.i}"><span><b>${esc(x.s.name)}</b><small>${x.r[1]} / ${x.r[2]} Tage</small></span><strong>${climateDiff(x.r[3])}</strong></button>`).join("")||'<div class="dwd-daily-empty">Noch kein Stationsrekord erreicht.</div>';document.querySelectorAll("#dwdDailyTopList [data-i],#dwdDailyBottomList [data-i],#dwdDailyRecordList [data-i]").forEach(b=>b.onclick=()=>{const i=+b.dataset.i,r=rm.get(i);if(r){selected=i;climateDetail(station(i),r,metric,meta);map.setView([station(i).lat,station(i).lon],Math.max(map.getZoom(),7))}});if(selected!=null&&rm.has(selected))climateDetail(station(selected),rm.get(selected),metric,meta);setTimeout(()=>map.invalidateSize(),50)}
function render(payload,iso){$("dwdDailyRecordTitle").textContent="Rekorde des Tages";const rm=new Map(payload.rows.map(r=>[+r[0],r])),m=mode();legend(m);initMap();layer.clearLayers();let anomalies=0,recs=0;for(const [i,r] of rm){if(r[3]!=null||r[4]!=null||r[12]!=null)anomalies++;if(r[5]||r[6])recs++} $("dwdDailyStationCount").textContent=rm.size.toLocaleString("de-DE");$("dwdDailyAnomalyCount").textContent=anomalies.toLocaleString("de-DE");$("dwdDailyRecordCount").textContent=recs.toLocaleString("de-DE");$("dwdDailyDataThrough").textContent=datefmt(iso);
 for(let i=0;i<idx.stations.length;i++){const s=station(i);if(!s||!Number.isFinite(s.lat)||!Number.isFinite(s.lon))continue;const r=rm.get(i),has=m[3]==="records"?!!(r?.[5]||r?.[6]):r?.[m[2]]!=null;const mk=L.circleMarker([s.lat,s.lon],{renderer,radius:has?5.2:3.2,weight:has?1.15:.55,color:"#26313a",opacity:has?.95:.48,fillColor:color(r,m),fillOpacity:has?.92:.32}).bindTooltip("<b>"+esc(s.name)+"</b><br>"+esc(val(r,m)));mk.on("click",()=>{if(r){selected=i;detail(s,r,iso)}});mk.addTo(layer)}
 let avail=[];for(const [i,r] of rm){const s=station(i);if(!s)continue;if(m[3]==="records"){if(r[5]||r[6])avail.push({s,r,v:r[5]?r[1]:r[2]})}else if(r[m[2]]!=null)avail.push({s,r,v:+r[m[2]]})}
 let top,bottom;if(m[3]==="records"){top=avail.filter(x=>x.r[5]).sort((a,b)=>(b.r[1]??-9999)-(a.r[1]??-9999)).slice(0,10);bottom=avail.filter(x=>x.r[6]).sort((a,b)=>(a.r[2]??9999)-(b.r[2]??9999)).slice(0,10);$("dwdDailyTopTitle").textContent="Tmax-Rekorde";$("dwdDailyBottomTitle").textContent="Tmin-Rekorde"}else{top=[...avail].sort((a,b)=>b.v-a.v).slice(0,10);bottom=[...avail].sort((a,b)=>a.v-b.v).slice(0,10);$("dwdDailyTopTitle").textContent="Top 10 · "+m[1];$("dwdDailyBottomTitle").textContent="Bottom 10 · "+m[1]}
 $("dwdDailyTopList").innerHTML=rowsHtml(top,m);$("dwdDailyBottomList").innerHTML=rowsHtml(bottom,m);
 const rr=[];for(const [i,r] of rm){if(r[5]||r[6]){const s=station(i);if(s)rr.push({s,r})}}
 const tmaxRecords=rr.filter(x=>x.r[5]).length,tminRecords=rr.filter(x=>x.r[6]).length;
 $("dwdDailyRecordSummary").textContent=`${rr.length.toLocaleString("de-DE")}/${rm.size.toLocaleString("de-DE")} Stationen · ${tmaxRecords.toLocaleString("de-DE")} Tmax · ${tminRecords.toLocaleString("de-DE")} Tmin`;
 $("dwdDailyRecordList").innerHTML=rr.length?rr.map(x=>`<button class="dwd-daily-row" data-i="${x.s.i}"><span><b>${esc(x.s.name)}</b><small>${esc(x.s.state)}</small></span><span>${x.r[5]?'<i class="dwd-daily-record-tag hot">Tmax</i>':""} ${x.r[6]?'<i class="dwd-daily-record-tag cold">Tmin</i>':""}</span></button>`).join(""):'<div class="dwd-daily-empty">Keine Rekorde an diesem Tag.</div>';
 document.querySelectorAll("#dwdDailyTopList [data-i],#dwdDailyBottomList [data-i],#dwdDailyRecordList [data-i]").forEach(b=>b.onclick=()=>{const i=+b.dataset.i,r=rm.get(i);if(r){selected=i;detail(station(i),r,iso);map.setView([station(i).lat,station(i).lon],Math.max(map.getZoom(),7))}});
 if(selected!=null&&rm.has(selected))detail(station(selected),rm.get(selected),iso);setTimeout(()=>map.invalidateSize(),50)}
async function draw(){try{await index();const m=mode(),isClimate=m[3]==="climate",dateInput=$("dwdDailyDate"),prev=$("dwdDailyPrev"),next=$("dwdDailyNext");dateInput.disabled=isClimate;prev.disabled=isClimate;next.disabled=isClimate;if(isClimate){$("dwdDailyStatus").textContent=m[1]+" wird geladen …";const p=await climate();renderClimate(p);$("dwdDailyStatus").classList.remove("error");$("dwdDailyStatus").textContent=m[1]+" · Stand "+datefmt(p.data_through)+" · "+(p.metrics?.[m[2]]?.rows?.length||0).toLocaleString("de-DE")+" Stationen · historischer Jahresrekord bis "+(idx.year-1);return}let iso=dateInput.value||idx.data_through;if(!idx.dates.includes(iso)){iso=idx.dates.filter(d=>d<=iso).at(-1)||idx.dates[0];dateInput.value=iso}$("dwdDailyStatus").textContent=datefmt(iso)+" wird geladen …";const p=await day(iso);render(p,iso);$("dwdDailyStatus").classList.remove("error");$("dwdDailyStatus").textContent=MODES[$("dwdDailyMetric").value][0]+" · "+datefmt(iso)+" · "+p.rows.length.toLocaleString("de-DE")+" Stationen · Referenz "+idx.reference_period}catch(e){console.error(e);$("dwdDailyStatus").classList.add("error");$("dwdDailyStatus").textContent="DWD-Tageskarte konnte nicht geladen werden: "+e.message}}
function bind(){if(bound)return;bound=true;$("dwdDailyMetric").onchange=draw;$("dwdDailyDate").onchange=draw;$("dwdDailyPrev").onclick=()=>{const i=idx.dates.indexOf($("dwdDailyDate").value);if(i>0){$("dwdDailyDate").value=idx.dates[i-1];draw()}};$("dwdDailyNext").onclick=()=>{const i=idx.dates.indexOf($("dwdDailyDate").value);if(i>=0&&i<idx.dates.length-1){$("dwdDailyDate").value=idx.dates[i+1];draw()}}}
async function load(){inject();try{await index();bind();initMap();const d=$("dwdDailyDate");d.min=idx.dates[0]||"";d.max=idx.data_through||"";if(!d.value)d.value=idx.data_through;$("dwdDailyReference").textContent="Tagesanomalien: Stationsmittel "+idx.reference_period+" · Kenntage: aktueller Jahresstand minus bisheriger Stations-Jahresrekord";await draw()}catch(e){$("dwdDailyStatus").classList.add("error");$("dwdDailyStatus").textContent="DWD-Tageskarte konnte nicht geladen werden: "+e.message}}
inject();window.ensureDwdDailyMapLoaded=load;
})();